<?php
  require 'vendor/phpmailer/phpmailer/PHPMailerAutoload.php';
  require 'email_server_settings.php';
  require 'mysql_server_settings.php';
  require 'genkey.php';
  require 'redirect.php';
  
  /**
   * You need to create a 'email_server_settings.php' file which contains:
   *   $smtp_hostname = "smtp.googlemail.com";
   *   $smtp_username = "[email address]@gmail.com";
   *   $smtp_password = "[password]";
   *   $smtp_port = 465;
   *   $smtp_security_method = "ssl";
   *   --> I've left this general stuff so you can send email from a gmail address, but I don't want to put this info into
   *       source control.  
   *       
   * You also need a 'mysql_server_settings.php' file with:
   *   $mysql_username = [username];
   *   $mysql_password = [password];
   *   $mysql_database_name = [database name];
   */

  $name = $_POST['new_subscriber_name'];
  $email = $_POST['new_subscriber_email'];
  
  $conn = mysqli_connect("localhost", $mysql_username, $mysql_password, $mysql_database_name); 
  
  if (!$conn) {
    die(mysqli_error($conn) . " -- (" . mysqli_errno($conn) . ")");
  }
  
  $matching_emails = mysqli_query($conn, "SELECT * FROM email_subscribers WHERE email = '{$email}';");

  if (!$matching_emails) {
    die(mysqli_error($conn) . " -- (" . mysqli_errno($conn) . ")");
  }
  
  // Do we already have this email address in the system?  If so, return to 
  // new_subscriber.php page.  
  if (mysqli_num_rows($matching_emails) > 0) {
    redirect_with_message("new_subscriber.php", "Email address {$email} is already in our database.");
  }
  
  // TODO: Fix SQL injection potential here
  $result = mysqli_query($conn, "INSERT INTO email_subscribers (name, email, status) VALUES ('{$name}', '{$email}', 'UN');");
  
  if (!$result) {
    die(mysqli_error($conn) . " -- (" . mysqli_errno($conn) . ")");
  }
  // If INSERT was successful, let's get the AUTO_INCREMENT id for later use
  $email_subscriber_id = mysqli_insert_id($conn);
  
  // At this point, the database row has been inserted, and we are about to 
  // send the confirmation email.  Before doing that, we need to generate the
  // confirmation key.  
    
  $confirm_key = generate_random_key();

  $host = "localhost";
  $app_dir = "~tom/email-subscriber-list";
  $url = "http://{$host}/{$app_dir}/confirm_subscriber.php?confirm_key={$confirm_key}";

  // NOTE: there is actually no SQL injection concern here, as the strings are
  //       generated by us...
  $insert_unconfirmed_subscriber_query = 
    "INSERT INTO unconfirmed_subscribers ";
  $insert_unconfirmed_subscriber_query .= 
    " (email_subscriber_id, confirm_key) "; 
  $insert_unconfirmed_subscriber_query .=
    "VALUES ({$email_subscriber_id}, '${confirm_key}');";
  
  $insert_unconfirmed_subscriber_result = 
    mysqli_query($conn, $insert_unconfirmed_subscriber_query);
  
  if (!$insert_unconfirmed_subscriber_result) {
    // We will leave this as a "just die and sit" error for now.
?>
<h3>Internal Error -- couldn't store confirm_key properly...</h3>
<p>Something went wrong!</p>
<p>Error: <?php echo mysqli_error($conn) . ':(' . mysqli_errno($conn) . ')'; ?>
</p>
<?php
    exit();
  }
  
  $mail = new PHPMailer();
  $mail->IsSMTP();
  $mail->CharSet = 'UTF-8';

  $mail->Host       = $smtp_hostname; // SMTP server example
  $mail->SMTPDebug  = 0;                     // enables SMTP debug information (for testing)
  $mail->SMTPAuth   = true;                  // enable SMTP authentication
  $mail->Port       = $smtp_port;                    // set the SMTP port for the GMAIL server
  $mail->SMTPSecure = $smtp_security_method;
  $mail->Username   = $smtp_username; // SMTP account username example
  $mail->From       = $smtp_username;
  $mail->FromName   = "Tom Mowad fanpage admin";
  $mail->Password   = $smtp_password;        // SMTP account password example
  
  $mail->addAddress($email, $name);
  
  $mail->Subject = "Confirm subscription - Tom Mowad's mailing list";
  
  $mail->Body = "Dear {$name},<br/>\n<br/>\nPlease click " . 
    "<a href=\"{$url}\">here</a> to confirm...";
  $mail->isHTML(true);
  
  if (!$mail->send()) {
    echo "Message could not be sent!";
    echo "Mailer error: " . $mail->ErrorInfo;
    exit();
  } else {
    // At this point, the database row was inserted, and a confirmation email was sent.
    redirect_with_message("list_subscribers.php", "User {$name} with email address {$email} has been added.");
  }
?>

